
// This file was auto-generated by ML.NET Model Builder. 

using Fooding;

// Create single instance of sample data from first line of dataset for model input
Fooding.ModelInput sampleData = new Fooding.ModelInput()
{
    Month = @"janv",
    Vacance = 6F,
    Nom = @"tomates",
    N = 950F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Qt with predicted Qt from sample data...\n\n");


Console.WriteLine($"Month: {@"janv"}");
Console.WriteLine($"Vacance: {6F}");
Console.WriteLine($"Nom: {@"tomates"}");
Console.WriteLine($"Qt: {100F}");
Console.WriteLine($"N: {950F}");


// Make a single prediction on the sample data and print results
var predictionResult = Fooding.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Qt: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

